# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'nineBase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nineBase
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  # target 'nineBase-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'nineBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'nineBase-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for nineBase-tvOS

#   target 'nineBase-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
